APP_NAME := auth
MAIN := cmd/server/main.go
PROTO_SRC := proto
PROTO_OUT := internal/platform/gen/go
PROTO_BREAKING_AGAINST ?= ../.git\#branch=origin/main,subdir=proto

.PHONY: run build clean proto proto-lint proto-breaking proto-clean tidy test test-cover test-race vet staticcheck lint setup-hooks licenses

# Run the main application
run:
	go run $(MAIN)

# Build the binary
build:
	go build -o bin/$(APP_NAME) $(MAIN)

# Clean build artifacts
clean:
	rm -rf bin

# Generate Go code from .proto definitions
proto:
	@echo "Generating Go gRPC code from proto files..."
	@mkdir -p $(PROTO_OUT)
	cd $(PROTO_SRC) && buf generate --template buf.gen.yaml .

proto-lint:
	cd $(PROTO_SRC) && buf lint .

proto-breaking:
	cd $(PROTO_SRC) && buf breaking . --against '$(PROTO_BREAKING_AGAINST)'

# Clean generated proto files
proto-clean:
	@echo "Cleaning generated proto files..."
	@rm -rf $(PROTO_OUT)

# Tidy up dependencies
tidy:
	go mod tidy

# Run all unit tests
test:
	go test ./... -count=1

# Run all unit tests with race detector
test-race:
	go test ./... -count=1 -race

vet:
	go vet ./...

staticcheck:
	go install honnef.co/go/tools/cmd/staticcheck@v0.7.0
	staticcheck ./...

lint: vet staticcheck

# Run unit tests and output an HTML coverage report (opens in browser).
# Folder exclusions are handled by codecov.yml on the Codecov side.
test-cover:
	go test ./... -count=1 -coverprofile=coverage.out
	go tool cover -html=coverage.out -o coverage.html
	@echo "Coverage report written to coverage.html"

# Install git hooks for pre-commit secret scanning
setup-hooks:
	git config core.hooksPath .githooks
	@echo "Git hooks installed — gitleaks will scan staged changes on commit"

# Check dependency licenses (fail on forbidden/restricted) and regenerate THIRD_PARTY_NOTICES.md.
# Apache-2.0 project: GPL/AGPL/LGPL and other copyleft licenses must not be linked.
licenses:
	go install github.com/google/go-licenses@latest
	go-licenses check ./... --disallowed_types=forbidden,restricted,reciprocal
	@printf '# Third-Party Notices\n\nGenerated by `make licenses` (github.com/google/go-licenses). See NOTICE for project copyright.\n\n' > THIRD_PARTY_NOTICES.md
	go-licenses report ./... 2>/dev/null | sort >> THIRD_PARTY_NOTICES.md
	@echo "Third-party notices written to THIRD_PARTY_NOTICES.md"
