// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const agentHeartbeat = `-- name: AgentHeartbeat :one
UPDATE agents
SET last_seen_at = now(), status = 'online', updated_at = now()
WHERE agent_uuid = $1 AND deleted_at IS NULL
RETURNING agent_id, agent_uuid, tenant_id, name, status, endpoint, version, capabilities, join_token_hash, join_token_used_at, client_cert_pem, bound_subject, last_seen_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

func (q *Queries) AgentHeartbeat(ctx context.Context, agentUuid uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, agentHeartbeat, agentUuid)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.AgentUuid,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Endpoint,
		&i.Version,
		&i.Capabilities,
		&i.JoinTokenHash,
		&i.JoinTokenUsedAt,
		&i.ClientCertPem,
		&i.BoundSubject,
		&i.LastSeenAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const bindAgentSubject = `-- name: BindAgentSubject :one
UPDATE agents
SET bound_subject = $2, updated_at = now()
WHERE agent_uuid = $1 AND deleted_at IS NULL
  AND (bound_subject = '' OR bound_subject = $2)
RETURNING agent_id, agent_uuid, tenant_id, name, status, endpoint, version, capabilities, join_token_hash, join_token_used_at, client_cert_pem, bound_subject, last_seen_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type BindAgentSubjectParams struct {
	AgentUuid    uuid.UUID `json:"agent_uuid"`
	BoundSubject string    `json:"bound_subject"`
}

// First authenticated Register wins: binds the verified token subject to the
// agent row. A Register presenting a DIFFERENT subject for an already-bound
// agent matches no rows, which the service surfaces as PermissionDenied — an
// enrolled agent identity can never be silently taken over by another
// principal that merely learned the agent's UUID.
func (q *Queries) BindAgentSubject(ctx context.Context, arg BindAgentSubjectParams) (Agent, error) {
	row := q.db.QueryRow(ctx, bindAgentSubject, arg.AgentUuid, arg.BoundSubject)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.AgentUuid,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Endpoint,
		&i.Version,
		&i.Capabilities,
		&i.JoinTokenHash,
		&i.JoinTokenUsedAt,
		&i.ClientCertPem,
		&i.BoundSubject,
		&i.LastSeenAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countAgentsByTenant = `-- name: CountAgentsByTenant :one
SELECT count(*) FROM agents WHERE tenant_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountAgentsByTenant(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (tenant_id, name, status, endpoint, version, capabilities, metadata, join_token_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING agent_id, agent_uuid, tenant_id, name, status, endpoint, version, capabilities, join_token_hash, join_token_used_at, client_cert_pem, bound_subject, last_seen_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateAgentParams struct {
	TenantID      int64  `json:"tenant_id"`
	Name          string `json:"name"`
	Status        string `json:"status"`
	Endpoint      string `json:"endpoint"`
	Version       string `json:"version"`
	Capabilities  []byte `json:"capabilities"`
	Metadata      []byte `json:"metadata"`
	JoinTokenHash string `json:"join_token_hash"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.TenantID,
		arg.Name,
		arg.Status,
		arg.Endpoint,
		arg.Version,
		arg.Capabilities,
		arg.Metadata,
		arg.JoinTokenHash,
	)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.AgentUuid,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Endpoint,
		&i.Version,
		&i.Capabilities,
		&i.JoinTokenHash,
		&i.JoinTokenUsedAt,
		&i.ClientCertPem,
		&i.BoundSubject,
		&i.LastSeenAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT agent_id, agent_uuid, tenant_id, name, status, endpoint, version, capabilities, join_token_hash, join_token_used_at, client_cert_pem, bound_subject, last_seen_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM agents WHERE agent_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAgentByID(ctx context.Context, agentID int64) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, agentID)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.AgentUuid,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Endpoint,
		&i.Version,
		&i.Capabilities,
		&i.JoinTokenHash,
		&i.JoinTokenUsedAt,
		&i.ClientCertPem,
		&i.BoundSubject,
		&i.LastSeenAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAgentByUUID = `-- name: GetAgentByUUID :one
SELECT agent_id, agent_uuid, tenant_id, name, status, endpoint, version, capabilities, join_token_hash, join_token_used_at, client_cert_pem, bound_subject, last_seen_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM agents WHERE agent_uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAgentByUUID(ctx context.Context, agentUuid uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByUUID, agentUuid)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.AgentUuid,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Endpoint,
		&i.Version,
		&i.Capabilities,
		&i.JoinTokenHash,
		&i.JoinTokenUsedAt,
		&i.ClientCertPem,
		&i.BoundSubject,
		&i.LastSeenAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAgentsByTenant = `-- name: ListAgentsByTenant :many
SELECT agent_id, agent_uuid, tenant_id, name, status, endpoint, version, capabilities, join_token_hash, join_token_used_at, client_cert_pem, bound_subject, last_seen_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM agents
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAgentsByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListAgentsByTenant(ctx context.Context, arg ListAgentsByTenantParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.AgentID,
			&i.AgentUuid,
			&i.TenantID,
			&i.Name,
			&i.Status,
			&i.Endpoint,
			&i.Version,
			&i.Capabilities,
			&i.JoinTokenHash,
			&i.JoinTokenUsedAt,
			&i.ClientCertPem,
			&i.BoundSubject,
			&i.LastSeenAt,
			&i.Metadata,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentEnrolled = `-- name: MarkAgentEnrolled :one
UPDATE agents
SET join_token_used_at = now(), client_cert_pem = $2, updated_at = now()
WHERE agent_uuid = $1 AND deleted_at IS NULL AND join_token_used_at IS NULL
RETURNING agent_id, agent_uuid, tenant_id, name, status, endpoint, version, capabilities, join_token_hash, join_token_used_at, client_cert_pem, bound_subject, last_seen_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type MarkAgentEnrolledParams struct {
	AgentUuid     uuid.UUID `json:"agent_uuid"`
	ClientCertPem string    `json:"client_cert_pem"`
}

func (q *Queries) MarkAgentEnrolled(ctx context.Context, arg MarkAgentEnrolledParams) (Agent, error) {
	row := q.db.QueryRow(ctx, markAgentEnrolled, arg.AgentUuid, arg.ClientCertPem)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.AgentUuid,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Endpoint,
		&i.Version,
		&i.Capabilities,
		&i.JoinTokenHash,
		&i.JoinTokenUsedAt,
		&i.ClientCertPem,
		&i.BoundSubject,
		&i.LastSeenAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteAgent = `-- name: SoftDeleteAgent :exec
UPDATE agents SET deleted_at = now(), updated_at = now()
WHERE agent_uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAgent(ctx context.Context, agentUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAgent, agentUuid)
	return err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :one
UPDATE agents
SET status = $2, endpoint = $3, version = $4, capabilities = $5, updated_at = now()
WHERE agent_uuid = $1 AND deleted_at IS NULL
RETURNING agent_id, agent_uuid, tenant_id, name, status, endpoint, version, capabilities, join_token_hash, join_token_used_at, client_cert_pem, bound_subject, last_seen_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateAgentStatusParams struct {
	AgentUuid    uuid.UUID `json:"agent_uuid"`
	Status       string    `json:"status"`
	Endpoint     string    `json:"endpoint"`
	Version      string    `json:"version"`
	Capabilities []byte    `json:"capabilities"`
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgentStatus,
		arg.AgentUuid,
		arg.Status,
		arg.Endpoint,
		arg.Version,
		arg.Capabilities,
	)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.AgentUuid,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Endpoint,
		&i.Version,
		&i.Capabilities,
		&i.JoinTokenHash,
		&i.JoinTokenUsedAt,
		&i.ClientCertPem,
		&i.BoundSubject,
		&i.LastSeenAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
