// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: control_plane.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getControlPlane = `-- name: GetControlPlane :one
SELECT id, auth_tenant_uuid, data, control_private_key_pem, setup_completed_at, created_at, updated_at FROM control_plane WHERE id = 1
`

func (q *Queries) GetControlPlane(ctx context.Context) (ControlPlane, error) {
	row := q.db.QueryRow(ctx, getControlPlane)
	var i ControlPlane
	err := row.Scan(
		&i.ID,
		&i.AuthTenantUuid,
		&i.Data,
		&i.ControlPrivateKeyPem,
		&i.SetupCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertControlPlane = `-- name: UpsertControlPlane :one
INSERT INTO control_plane (id, auth_tenant_uuid, data, control_private_key_pem, setup_completed_at)
VALUES (1, $1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET auth_tenant_uuid        = EXCLUDED.auth_tenant_uuid,
    data                    = EXCLUDED.data,
    control_private_key_pem = EXCLUDED.control_private_key_pem,
    setup_completed_at      = EXCLUDED.setup_completed_at,
    updated_at              = now()
RETURNING id, auth_tenant_uuid, data, control_private_key_pem, setup_completed_at, created_at, updated_at
`

type UpsertControlPlaneParams struct {
	AuthTenantUuid       pgtype.UUID        `json:"auth_tenant_uuid"`
	Data                 []byte             `json:"data"`
	ControlPrivateKeyPem string             `json:"control_private_key_pem"`
	SetupCompletedAt     pgtype.Timestamptz `json:"setup_completed_at"`
}

func (q *Queries) UpsertControlPlane(ctx context.Context, arg UpsertControlPlaneParams) (ControlPlane, error) {
	row := q.db.QueryRow(ctx, upsertControlPlane,
		arg.AuthTenantUuid,
		arg.Data,
		arg.ControlPrivateKeyPem,
		arg.SetupCompletedAt,
	)
	var i ControlPlane
	err := row.Scan(
		&i.ID,
		&i.AuthTenantUuid,
		&i.Data,
		&i.ControlPrivateKeyPem,
		&i.SetupCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
