// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_template.sql

package storage

import (
	"context"
)

const countDeploymentTemplates = `-- name: CountDeploymentTemplates :one
SELECT count(*) FROM deployment_templates WHERE deleted_at IS NULL
`

func (q *Queries) CountDeploymentTemplates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDeploymentTemplates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeploymentTemplate = `-- name: CreateDeploymentTemplate :one
INSERT INTO deployment_templates (name, version, capability, image, parameters, spec, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING template_id, template_uuid, name, version, capability, image, parameters, spec, metadata, created_at, updated_at, deleted_at
`

type CreateDeploymentTemplateParams struct {
	Name       string `json:"name"`
	Version    string `json:"version"`
	Capability string `json:"capability"`
	Image      string `json:"image"`
	Parameters []byte `json:"parameters"`
	Spec       []byte `json:"spec"`
	Metadata   []byte `json:"metadata"`
}

func (q *Queries) CreateDeploymentTemplate(ctx context.Context, arg CreateDeploymentTemplateParams) (DeploymentTemplate, error) {
	row := q.db.QueryRow(ctx, createDeploymentTemplate,
		arg.Name,
		arg.Version,
		arg.Capability,
		arg.Image,
		arg.Parameters,
		arg.Spec,
		arg.Metadata,
	)
	var i DeploymentTemplate
	err := row.Scan(
		&i.TemplateID,
		&i.TemplateUuid,
		&i.Name,
		&i.Version,
		&i.Capability,
		&i.Image,
		&i.Parameters,
		&i.Spec,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDeploymentTemplate = `-- name: GetDeploymentTemplate :one
SELECT template_id, template_uuid, name, version, capability, image, parameters, spec, metadata, created_at, updated_at, deleted_at FROM deployment_templates
WHERE name = $1 AND version = $2 AND deleted_at IS NULL
`

type GetDeploymentTemplateParams struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

func (q *Queries) GetDeploymentTemplate(ctx context.Context, arg GetDeploymentTemplateParams) (DeploymentTemplate, error) {
	row := q.db.QueryRow(ctx, getDeploymentTemplate, arg.Name, arg.Version)
	var i DeploymentTemplate
	err := row.Scan(
		&i.TemplateID,
		&i.TemplateUuid,
		&i.Name,
		&i.Version,
		&i.Capability,
		&i.Image,
		&i.Parameters,
		&i.Spec,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDeploymentTemplates = `-- name: ListDeploymentTemplates :many
SELECT template_id, template_uuid, name, version, capability, image, parameters, spec, metadata, created_at, updated_at, deleted_at FROM deployment_templates
WHERE deleted_at IS NULL
ORDER BY name ASC, version ASC
LIMIT $1 OFFSET $2
`

type ListDeploymentTemplatesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDeploymentTemplates(ctx context.Context, arg ListDeploymentTemplatesParams) ([]DeploymentTemplate, error) {
	rows, err := q.db.Query(ctx, listDeploymentTemplates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentTemplate{}
	for rows.Next() {
		var i DeploymentTemplate
		if err := rows.Scan(
			&i.TemplateID,
			&i.TemplateUuid,
			&i.Name,
			&i.Version,
			&i.Capability,
			&i.Image,
			&i.Parameters,
			&i.Spec,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDeploymentTemplate = `-- name: SoftDeleteDeploymentTemplate :exec
UPDATE deployment_templates SET deleted_at = now(), updated_at = now()
WHERE name = $1 AND version = $2 AND deleted_at IS NULL
`

type SoftDeleteDeploymentTemplateParams struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

func (q *Queries) SoftDeleteDeploymentTemplate(ctx context.Context, arg SoftDeleteDeploymentTemplateParams) error {
	_, err := q.db.Exec(ctx, softDeleteDeploymentTemplate, arg.Name, arg.Version)
	return err
}
