// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	AgentID         int64              `json:"agent_id"`
	AgentUuid       uuid.UUID          `json:"agent_uuid"`
	TenantID        int64              `json:"tenant_id"`
	Name            string             `json:"name"`
	Status          string             `json:"status"`
	Endpoint        string             `json:"endpoint"`
	Version         string             `json:"version"`
	Capabilities    []byte             `json:"capabilities"`
	JoinTokenHash   string             `json:"join_token_hash"`
	JoinTokenUsedAt pgtype.Timestamptz `json:"join_token_used_at"`
	ClientCertPem   string             `json:"client_cert_pem"`
	BoundSubject    string             `json:"bound_subject"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	Metadata        []byte             `json:"metadata"`
	CreatedBy       pgtype.Int8        `json:"created_by"`
	UpdatedBy       pgtype.Int8        `json:"updated_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type ControlPlane struct {
	ID                   int32              `json:"id"`
	AuthTenantUuid       pgtype.UUID        `json:"auth_tenant_uuid"`
	Data                 []byte             `json:"data"`
	ControlPrivateKeyPem string             `json:"control_private_key_pem"`
	DeploymentMode       string             `json:"deployment_mode"`
	SetupCompletedAt     pgtype.Timestamptz `json:"setup_completed_at"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type DeploymentTemplate struct {
	TemplateID   int64              `json:"template_id"`
	TemplateUuid uuid.UUID          `json:"template_uuid"`
	Name         string             `json:"name"`
	Version      string             `json:"version"`
	Capability   string             `json:"capability"`
	Image        string             `json:"image"`
	Parameters   []byte             `json:"parameters"`
	Spec         []byte             `json:"spec"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type PlatformEvent struct {
	EventID     int64       `json:"event_id"`
	EventUuid   uuid.UUID   `json:"event_uuid"`
	TenantID    pgtype.Int8 `json:"tenant_id"`
	Kind        string      `json:"kind"`
	Severity    string      `json:"severity"`
	SubjectType string      `json:"subject_type"`
	SubjectUuid pgtype.UUID `json:"subject_uuid"`
	Message     string      `json:"message"`
	Details     []byte      `json:"details"`
	CreatedAt   time.Time   `json:"created_at"`
}

type Project struct {
	ProjectID   int64              `json:"project_id"`
	ProjectUuid uuid.UUID          `json:"project_uuid"`
	TenantID    int64              `json:"tenant_id"`
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Metadata    []byte             `json:"metadata"`
	CreatedBy   pgtype.Int8        `json:"created_by"`
	UpdatedBy   pgtype.Int8        `json:"updated_by"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Provider struct {
	ProviderID   int64              `json:"provider_id"`
	ProviderUuid uuid.UUID          `json:"provider_uuid"`
	TenantID     int64              `json:"tenant_id"`
	Name         string             `json:"name"`
	ResourceKind string             `json:"resource_kind"`
	Driver       string             `json:"driver"`
	Config       []byte             `json:"config"`
	Status       string             `json:"status"`
	Metadata     []byte             `json:"metadata"`
	CreatedBy    pgtype.Int8        `json:"created_by"`
	UpdatedBy    pgtype.Int8        `json:"updated_by"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Resource struct {
	ResourceID         int64              `json:"resource_id"`
	ResourceUuid       uuid.UUID          `json:"resource_uuid"`
	TenantID           int64              `json:"tenant_id"`
	ProjectID          int64              `json:"project_id"`
	ProviderID         pgtype.Int8        `json:"provider_id"`
	AgentID            pgtype.Int8        `json:"agent_id"`
	OwnerResourceID    pgtype.Int8        `json:"owner_resource_id"`
	MrnService         string             `json:"mrn_service"`
	MrnTenant          string             `json:"mrn_tenant"`
	MrnProject         string             `json:"mrn_project"`
	MrnResourceType    string             `json:"mrn_resource_type"`
	MrnResourcePath    string             `json:"mrn_resource_path"`
	Kind               string             `json:"kind"`
	Name               string             `json:"name"`
	State              string             `json:"state"`
	Health             string             `json:"health"`
	Spec               []byte             `json:"spec"`
	Status             []byte             `json:"status"`
	Generation         int64              `json:"generation"`
	ObservedGeneration int64              `json:"observed_generation"`
	LeasedUntil        pgtype.Timestamptz `json:"leased_until"`
	Attempts           int32              `json:"attempts"`
	NextAttemptAt      pgtype.Timestamptz `json:"next_attempt_at"`
	Metadata           []byte             `json:"metadata"`
	CreatedBy          pgtype.Int8        `json:"created_by"`
	UpdatedBy          pgtype.Int8        `json:"updated_by"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type Service struct {
	ServiceID    int64              `json:"service_id"`
	ServiceUuid  uuid.UUID          `json:"service_uuid"`
	TenantID     int64              `json:"tenant_id"`
	Name         string             `json:"name"`
	Kind         string             `json:"kind"`
	Status       string             `json:"status"`
	Endpoint     string             `json:"endpoint"`
	Version      string             `json:"version"`
	Metadata     []byte             `json:"metadata"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	CreatedBy    pgtype.Int8        `json:"created_by"`
	UpdatedBy    pgtype.Int8        `json:"updated_by"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	IsSystem     bool               `json:"is_system"`
}

type Tenant struct {
	TenantID       int64              `json:"tenant_id"`
	TenantUuid     uuid.UUID          `json:"tenant_uuid"`
	AuthTenantUuid pgtype.UUID        `json:"auth_tenant_uuid"`
	Name           string             `json:"name"`
	DisplayName    string             `json:"display_name"`
	Status         string             `json:"status"`
	IsSystem       bool               `json:"is_system"`
	Metadata       []byte             `json:"metadata"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	UpdatedBy      pgtype.Int8        `json:"updated_by"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}
