// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	AgentID      int64              `json:"agent_id"`
	AgentUuid    uuid.UUID          `json:"agent_uuid"`
	TenantID     int64              `json:"tenant_id"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	Endpoint     string             `json:"endpoint"`
	Version      string             `json:"version"`
	Capabilities []byte             `json:"capabilities"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	Metadata     []byte             `json:"metadata"`
	CreatedBy    pgtype.Int8        `json:"created_by"`
	UpdatedBy    pgtype.Int8        `json:"updated_by"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Project struct {
	ProjectID   int64              `json:"project_id"`
	ProjectUuid uuid.UUID          `json:"project_uuid"`
	TenantID    int64              `json:"tenant_id"`
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Metadata    []byte             `json:"metadata"`
	CreatedBy   pgtype.Int8        `json:"created_by"`
	UpdatedBy   pgtype.Int8        `json:"updated_by"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Provider struct {
	ProviderID   int64              `json:"provider_id"`
	ProviderUuid uuid.UUID          `json:"provider_uuid"`
	TenantID     int64              `json:"tenant_id"`
	Name         string             `json:"name"`
	ResourceKind string             `json:"resource_kind"`
	Driver       string             `json:"driver"`
	Config       []byte             `json:"config"`
	Status       string             `json:"status"`
	Metadata     []byte             `json:"metadata"`
	CreatedBy    pgtype.Int8        `json:"created_by"`
	UpdatedBy    pgtype.Int8        `json:"updated_by"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Resource struct {
	ResourceID         int64              `json:"resource_id"`
	ResourceUuid       uuid.UUID          `json:"resource_uuid"`
	TenantID           int64              `json:"tenant_id"`
	ProjectID          int64              `json:"project_id"`
	ProviderID         pgtype.Int8        `json:"provider_id"`
	AgentID            pgtype.Int8        `json:"agent_id"`
	OwnerResourceID    pgtype.Int8        `json:"owner_resource_id"`
	Kind               string             `json:"kind"`
	Name               string             `json:"name"`
	State              string             `json:"state"`
	Spec               []byte             `json:"spec"`
	Status             []byte             `json:"status"`
	Generation         int64              `json:"generation"`
	ObservedGeneration int64              `json:"observed_generation"`
	Metadata           []byte             `json:"metadata"`
	CreatedBy          pgtype.Int8        `json:"created_by"`
	UpdatedBy          pgtype.Int8        `json:"updated_by"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type Service struct {
	ServiceID    int64              `json:"service_id"`
	ServiceUuid  uuid.UUID          `json:"service_uuid"`
	TenantID     int64              `json:"tenant_id"`
	Name         string             `json:"name"`
	Kind         string             `json:"kind"`
	Status       string             `json:"status"`
	Endpoint     string             `json:"endpoint"`
	Version      string             `json:"version"`
	Metadata     []byte             `json:"metadata"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	CreatedBy    pgtype.Int8        `json:"created_by"`
	UpdatedBy    pgtype.Int8        `json:"updated_by"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	IsSystem     bool               `json:"is_system"`
}

type Tenant struct {
	TenantID       int64              `json:"tenant_id"`
	TenantUuid     uuid.UUID          `json:"tenant_uuid"`
	AuthTenantUuid pgtype.UUID        `json:"auth_tenant_uuid"`
	Name           string             `json:"name"`
	DisplayName    string             `json:"display_name"`
	Status         string             `json:"status"`
	IsSystem       bool               `json:"is_system"`
	Metadata       []byte             `json:"metadata"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	UpdatedBy      pgtype.Int8        `json:"updated_by"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}
