// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_event.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlatformEvents = `-- name: CountPlatformEvents :one
SELECT count(*) FROM platform_events
`

func (q *Queries) CountPlatformEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlatformEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlatformEvent = `-- name: CreatePlatformEvent :one
INSERT INTO platform_events (tenant_id, kind, severity, subject_type, subject_uuid, message, details)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING event_id, event_uuid, tenant_id, kind, severity, subject_type, subject_uuid, message, details, created_at
`

type CreatePlatformEventParams struct {
	TenantID    pgtype.Int8 `json:"tenant_id"`
	Kind        string      `json:"kind"`
	Severity    string      `json:"severity"`
	SubjectType string      `json:"subject_type"`
	SubjectUuid pgtype.UUID `json:"subject_uuid"`
	Message     string      `json:"message"`
	Details     []byte      `json:"details"`
}

func (q *Queries) CreatePlatformEvent(ctx context.Context, arg CreatePlatformEventParams) (PlatformEvent, error) {
	row := q.db.QueryRow(ctx, createPlatformEvent,
		arg.TenantID,
		arg.Kind,
		arg.Severity,
		arg.SubjectType,
		arg.SubjectUuid,
		arg.Message,
		arg.Details,
	)
	var i PlatformEvent
	err := row.Scan(
		&i.EventID,
		&i.EventUuid,
		&i.TenantID,
		&i.Kind,
		&i.Severity,
		&i.SubjectType,
		&i.SubjectUuid,
		&i.Message,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const listPlatformEvents = `-- name: ListPlatformEvents :many
SELECT event_id, event_uuid, tenant_id, kind, severity, subject_type, subject_uuid, message, details, created_at FROM platform_events
ORDER BY created_at DESC, event_id DESC
LIMIT $1 OFFSET $2
`

type ListPlatformEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Newest first: an operator reading the escalation log wants the current
// incident, not the install's first boot.
func (q *Queries) ListPlatformEvents(ctx context.Context, arg ListPlatformEventsParams) ([]PlatformEvent, error) {
	rows, err := q.db.Query(ctx, listPlatformEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformEvent{}
	for rows.Next() {
		var i PlatformEvent
		if err := rows.Scan(
			&i.EventID,
			&i.EventUuid,
			&i.TenantID,
			&i.Kind,
			&i.Severity,
			&i.SubjectType,
			&i.SubjectUuid,
			&i.Message,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformEventsBySubject = `-- name: ListPlatformEventsBySubject :many
SELECT event_id, event_uuid, tenant_id, kind, severity, subject_type, subject_uuid, message, details, created_at FROM platform_events
WHERE subject_type = $1 AND subject_uuid = $2
ORDER BY created_at DESC, event_id DESC
LIMIT $3 OFFSET $4
`

type ListPlatformEventsBySubjectParams struct {
	SubjectType string      `json:"subject_type"`
	SubjectUuid pgtype.UUID `json:"subject_uuid"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

// The incident timeline for one agent/resource/service.
func (q *Queries) ListPlatformEventsBySubject(ctx context.Context, arg ListPlatformEventsBySubjectParams) ([]PlatformEvent, error) {
	rows, err := q.db.Query(ctx, listPlatformEventsBySubject,
		arg.SubjectType,
		arg.SubjectUuid,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformEvent{}
	for rows.Next() {
		var i PlatformEvent
		if err := rows.Scan(
			&i.EventID,
			&i.EventUuid,
			&i.TenantID,
			&i.Kind,
			&i.Severity,
			&i.SubjectType,
			&i.SubjectUuid,
			&i.Message,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
