// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const countProjectsByTenant = `-- name: CountProjectsByTenant :one
SELECT count(*) FROM projects WHERE tenant_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountProjectsByTenant(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (tenant_id, name, display_name, description, status, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING project_id, project_uuid, tenant_id, name, display_name, description, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	TenantID    int64  `json:"tenant_id"`
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
	Description string `json:"description"`
	Status      string `json:"status"`
	Metadata    []byte `json:"metadata"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.TenantID,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.Status,
		arg.Metadata,
	)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.ProjectUuid,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT project_id, project_uuid, tenant_id, name, display_name, description, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM projects WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectByID(ctx context.Context, projectID int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, projectID)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.ProjectUuid,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByTenantAndName = `-- name: GetProjectByTenantAndName :one
SELECT project_id, project_uuid, tenant_id, name, display_name, description, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM projects WHERE tenant_id = $1 AND name = $2 AND deleted_at IS NULL
`

type GetProjectByTenantAndNameParams struct {
	TenantID int64  `json:"tenant_id"`
	Name     string `json:"name"`
}

func (q *Queries) GetProjectByTenantAndName(ctx context.Context, arg GetProjectByTenantAndNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByTenantAndName, arg.TenantID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.ProjectUuid,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByUUID = `-- name: GetProjectByUUID :one
SELECT project_id, project_uuid, tenant_id, name, display_name, description, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM projects WHERE project_uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectByUUID(ctx context.Context, projectUuid uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByUUID, projectUuid)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.ProjectUuid,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjectsByTenant = `-- name: ListProjectsByTenant :many
SELECT project_id, project_uuid, tenant_id, name, display_name, description, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM projects
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectsByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListProjectsByTenant(ctx context.Context, arg ListProjectsByTenantParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ProjectID,
			&i.ProjectUuid,
			&i.TenantID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Status,
			&i.Metadata,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects SET deleted_at = now(), updated_at = now()
WHERE project_uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProject(ctx context.Context, projectUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProject, projectUuid)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET display_name = $2, description = $3, status = $4, metadata = $5, updated_at = now()
WHERE project_uuid = $1 AND deleted_at IS NULL
RETURNING project_id, project_uuid, tenant_id, name, display_name, description, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	ProjectUuid uuid.UUID `json:"project_uuid"`
	DisplayName string    `json:"display_name"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	Metadata    []byte    `json:"metadata"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ProjectUuid,
		arg.DisplayName,
		arg.Description,
		arg.Status,
		arg.Metadata,
	)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.ProjectUuid,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
