// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const countProvidersByTenant = `-- name: CountProvidersByTenant :one
SELECT count(*) FROM providers WHERE tenant_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountProvidersByTenant(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProvidersByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (tenant_id, name, resource_kind, driver, config, status, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING provider_id, provider_uuid, tenant_id, name, resource_kind, driver, config, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateProviderParams struct {
	TenantID     int64  `json:"tenant_id"`
	Name         string `json:"name"`
	ResourceKind string `json:"resource_kind"`
	Driver       string `json:"driver"`
	Config       []byte `json:"config"`
	Status       string `json:"status"`
	Metadata     []byte `json:"metadata"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.TenantID,
		arg.Name,
		arg.ResourceKind,
		arg.Driver,
		arg.Config,
		arg.Status,
		arg.Metadata,
	)
	var i Provider
	err := row.Scan(
		&i.ProviderID,
		&i.ProviderUuid,
		&i.TenantID,
		&i.Name,
		&i.ResourceKind,
		&i.Driver,
		&i.Config,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT provider_id, provider_uuid, tenant_id, name, resource_kind, driver, config, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM providers WHERE provider_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProviderByID(ctx context.Context, providerID int64) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, providerID)
	var i Provider
	err := row.Scan(
		&i.ProviderID,
		&i.ProviderUuid,
		&i.TenantID,
		&i.Name,
		&i.ResourceKind,
		&i.Driver,
		&i.Config,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProviderByUUID = `-- name: GetProviderByUUID :one
SELECT provider_id, provider_uuid, tenant_id, name, resource_kind, driver, config, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM providers WHERE provider_uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProviderByUUID(ctx context.Context, providerUuid uuid.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByUUID, providerUuid)
	var i Provider
	err := row.Scan(
		&i.ProviderID,
		&i.ProviderUuid,
		&i.TenantID,
		&i.Name,
		&i.ResourceKind,
		&i.Driver,
		&i.Config,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProvidersByKind = `-- name: ListProvidersByKind :many
SELECT provider_id, provider_uuid, tenant_id, name, resource_kind, driver, config, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM providers
WHERE tenant_id = $1 AND resource_kind = $2 AND status = 'active' AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListProvidersByKindParams struct {
	TenantID     int64  `json:"tenant_id"`
	ResourceKind string `json:"resource_kind"`
}

func (q *Queries) ListProvidersByKind(ctx context.Context, arg ListProvidersByKindParams) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProvidersByKind, arg.TenantID, arg.ResourceKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ProviderID,
			&i.ProviderUuid,
			&i.TenantID,
			&i.Name,
			&i.ResourceKind,
			&i.Driver,
			&i.Config,
			&i.Status,
			&i.Metadata,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersByTenant = `-- name: ListProvidersByTenant :many
SELECT provider_id, provider_uuid, tenant_id, name, resource_kind, driver, config, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM providers
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProvidersByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListProvidersByTenant(ctx context.Context, arg ListProvidersByTenantParams) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProvidersByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ProviderID,
			&i.ProviderUuid,
			&i.TenantID,
			&i.Name,
			&i.ResourceKind,
			&i.Driver,
			&i.Config,
			&i.Status,
			&i.Metadata,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProvider = `-- name: SoftDeleteProvider :exec
UPDATE providers SET deleted_at = now(), updated_at = now()
WHERE provider_uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProvider(ctx context.Context, providerUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProvider, providerUuid)
	return err
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers
SET driver = $2, config = $3, status = $4, metadata = $5, updated_at = now()
WHERE provider_uuid = $1 AND deleted_at IS NULL
RETURNING provider_id, provider_uuid, tenant_id, name, resource_kind, driver, config, status, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateProviderParams struct {
	ProviderUuid uuid.UUID `json:"provider_uuid"`
	Driver       string    `json:"driver"`
	Config       []byte    `json:"config"`
	Status       string    `json:"status"`
	Metadata     []byte    `json:"metadata"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.ProviderUuid,
		arg.Driver,
		arg.Config,
		arg.Status,
		arg.Metadata,
	)
	var i Provider
	err := row.Scan(
		&i.ProviderID,
		&i.ProviderUuid,
		&i.TenantID,
		&i.Name,
		&i.ResourceKind,
		&i.Driver,
		&i.Config,
		&i.Status,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
