// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AgentHeartbeat(ctx context.Context, agentUuid uuid.UUID) (Agent, error)
	// The gateway's single write path for agent status reports. The service layer
	// computes the resulting state / attempts / backoff in Go; this statement
	// applies them atomically and ALWAYS releases the dispatch lease (a report is
	// the agent's answer for the leased item). observed_generation only moves
	// forward (GREATEST) so a stale drift report can never rewind convergence
	// progress; failure paths pass 0 to leave it untouched. `finalize` stamps
	// deleted_at — the terminal step of the teardown protocol after an agent
	// reports the workload removed.
	ApplyAgentReport(ctx context.Context, arg ApplyAgentReportParams) (Resource, error)
	AssignResourceAgent(ctx context.Context, arg AssignResourceAgentParams) (Resource, error)
	// First authenticated Register wins: binds the verified token subject to the
	// agent row. A Register presenting a DIFFERENT subject for an already-bound
	// agent matches no rows, which the service surfaces as PermissionDenied — an
	// enrolled agent identity can never be silently taken over by another
	// principal that merely learned the agent's UUID.
	BindAgentSubject(ctx context.Context, arg BindAgentSubjectParams) (Agent, error)
	// PullWork's atomic claim. Feed rules match ListOutOfSyncResources, scoped to
	// items already assigned to the calling agent OR unassigned (first claim is
	// sticky: agent_id is stamped and later pulls by other agents skip the row).
	// The FOR UPDATE SKIP LOCKED subselect + single UPDATE make it impossible for
	// two concurrent agents to claim the same item; the lease keeps the item out
	// of the feed until it expires or a status report releases it.
	ClaimAgentWork(ctx context.Context, arg ClaimAgentWorkParams) ([]Resource, error)
	CountAgentsByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountDeploymentTemplates(ctx context.Context) (int64, error)
	CountProjectsByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountProvidersByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountResourcesByProject(ctx context.Context, projectID int64) (int64, error)
	CountServicesByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountTenants(ctx context.Context) (int64, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateDeploymentTemplate(ctx context.Context, arg CreateDeploymentTemplateParams) (DeploymentTemplate, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	GetAgentByID(ctx context.Context, agentID int64) (Agent, error)
	GetAgentByUUID(ctx context.Context, agentUuid uuid.UUID) (Agent, error)
	GetControlPlane(ctx context.Context) (ControlPlane, error)
	GetDeploymentTemplate(ctx context.Context, arg GetDeploymentTemplateParams) (DeploymentTemplate, error)
	GetProjectByID(ctx context.Context, projectID int64) (Project, error)
	GetProjectByTenantAndName(ctx context.Context, arg GetProjectByTenantAndNameParams) (Project, error)
	GetProjectByUUID(ctx context.Context, projectUuid uuid.UUID) (Project, error)
	GetProviderByID(ctx context.Context, providerID int64) (Provider, error)
	GetProviderByUUID(ctx context.Context, providerUuid uuid.UUID) (Provider, error)
	GetResourceByID(ctx context.Context, resourceID int64) (Resource, error)
	GetResourceByUUID(ctx context.Context, resourceUuid uuid.UUID) (Resource, error)
	GetServiceByID(ctx context.Context, serviceID int64) (Service, error)
	GetServiceByTenantAndName(ctx context.Context, arg GetServiceByTenantAndNameParams) (Service, error)
	GetServiceByUUID(ctx context.Context, serviceUuid uuid.UUID) (Service, error)
	// The platform's root tenant — the single required system tenant.
	GetSystemTenant(ctx context.Context) (Tenant, error)
	GetTenantByID(ctx context.Context, tenantID int64) (Tenant, error)
	GetTenantByName(ctx context.Context, name string) (Tenant, error)
	GetTenantByUUID(ctx context.Context, tenantUuid uuid.UUID) (Tenant, error)
	ListAgentsByTenant(ctx context.Context, arg ListAgentsByTenantParams) ([]Agent, error)
	ListDeploymentTemplates(ctx context.Context, arg ListDeploymentTemplatesParams) ([]DeploymentTemplate, error)
	// The reconciler's work feed (read-only variant; the gateway uses ClaimAgentWork
	// which additionally stamps the lease + agent assignment). A row is fed when:
	//   * its observed state lags its spec, OR it is being torn down ('deleting'),
	//     OR a prior attempt failed retryably ('error');
	//   * it is not parked as 'failed' (budget exhausted — only a spec change
	//     re-arms it);
	//   * no dispatch lease is active and any retry backoff has elapsed.
	ListOutOfSyncResources(ctx context.Context, limit int32) ([]Resource, error)
	ListProjectsByTenant(ctx context.Context, arg ListProjectsByTenantParams) ([]Project, error)
	ListProvidersByKind(ctx context.Context, arg ListProvidersByKindParams) ([]Provider, error)
	ListProvidersByTenant(ctx context.Context, arg ListProvidersByTenantParams) ([]Provider, error)
	ListResourcesByProject(ctx context.Context, arg ListResourcesByProjectParams) ([]Resource, error)
	ListResourcesByTenant(ctx context.Context, arg ListResourcesByTenantParams) ([]Resource, error)
	ListServicesByTenant(ctx context.Context, arg ListServicesByTenantParams) ([]Service, error)
	// The platform's system services — the ones Core must keep running at all times.
	ListSystemServices(ctx context.Context) ([]Service, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	MarkAgentEnrolled(ctx context.Context, arg MarkAgentEnrolledParams) (Agent, error)
	// Deletion is a desired-state change, not an immediate erase: the row flips to
	// state='deleting' but keeps deleted_at NULL so it stays IN the work feed and
	// PullWork ships it to its agent as a teardown envelope. Only the agent's
	// "removed" report finalizes the delete (ApplyAgentReport with finalize) —
	// otherwise the workload would keep running on the host with no record of it.
	MarkResourceDeleting(ctx context.Context, resourceUuid uuid.UUID) error
	SoftDeleteAgent(ctx context.Context, agentUuid uuid.UUID) error
	SoftDeleteDeploymentTemplate(ctx context.Context, arg SoftDeleteDeploymentTemplateParams) error
	SoftDeleteProject(ctx context.Context, projectUuid uuid.UUID) error
	SoftDeleteProvider(ctx context.Context, providerUuid uuid.UUID) error
	SoftDeleteService(ctx context.Context, serviceUuid uuid.UUID) error
	SoftDeleteTenant(ctx context.Context, tenantUuid uuid.UUID) error
	UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (Agent, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error)
	// A spec change bumps generation and re-arms the reconciler (state -> pending).
	// It also resets the retry budget (attempts/next_attempt_at): a resource parked
	// as 'failed' after exhausting its budget gets a fresh budget only when its
	// desired state actually changes — never by the failing spec being retried
	// forever on its own.
	UpdateResourceSpec(ctx context.Context, arg UpdateResourceSpecParams) (Resource, error)
	// The reconciler writes observed state back, marking how far it has caught up.
	UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (Resource, error)
	UpdateServiceStatus(ctx context.Context, arg UpdateServiceStatusParams) (Service, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpsertControlPlane(ctx context.Context, arg UpsertControlPlaneParams) (ControlPlane, error)
}

var _ Querier = (*Queries)(nil)
