// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// The liveness write, and also the RECOVERY path: it stamps last_seen_at AND
	// forces status back to 'online', so an agent the sweeper marked 'offline'
	// returns to online on its very next beat with no extra reconciliation. The two
	// writes belong in one statement precisely so "seen" and "online" can never
	// disagree.
	AgentHeartbeat(ctx context.Context, agentUuid uuid.UUID) (Agent, error)
	// The gateway's single write path for agent status reports. The service layer
	// computes the resulting state / attempts / backoff in Go; this statement
	// applies them atomically and ALWAYS releases the dispatch lease (a report is
	// the agent's answer for the leased item). observed_generation only moves
	// forward (GREATEST) so a stale drift report can never rewind convergence
	// progress; failure paths pass 0 to leave it untouched. `finalize` stamps
	// deleted_at — the terminal step of the teardown protocol after an agent
	// reports the workload removed.
	// `health` is promoted out of the reported status JSON into its own column so
	// supervision can act on unhealthy-but-running without parsing JSONB: "running"
	// is not "working" (see 00006_create_resources.sql).
	ApplyAgentReport(ctx context.Context, arg ApplyAgentReportParams) (Resource, error)
	AssignResourceAgent(ctx context.Context, arg AssignResourceAgentParams) (Resource, error)
	// First authenticated Register wins: binds the verified token subject to the
	// agent row. A Register presenting a DIFFERENT subject for an already-bound
	// agent matches no rows, which the service surfaces as PermissionDenied — an
	// enrolled agent identity can never be silently taken over by another
	// principal that merely learned the agent's UUID.
	BindAgentSubject(ctx context.Context, arg BindAgentSubjectParams) (Agent, error)
	// PullWork's atomic claim. Feed rules match ListOutOfSyncResources, scoped to
	// items already assigned to the calling agent OR unassigned (first claim is
	// sticky: agent_id is stamped and later pulls by other agents skip the row).
	// The FOR UPDATE SKIP LOCKED subselect + single UPDATE make it impossible for
	// two concurrent agents to claim the same item; the lease keeps the item out
	// of the feed until it expires or a status report releases it.
	ClaimAgentWork(ctx context.Context, arg ClaimAgentWorkParams) ([]Resource, error)
	CountAgentsByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountDeploymentTemplates(ctx context.Context) (int64, error)
	CountPlatformEvents(ctx context.Context) (int64, error)
	CountProjectsByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountProvidersByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountResourcesByProject(ctx context.Context, projectID int64) (int64, error)
	CountServicesByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountTenants(ctx context.Context) (int64, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateDeploymentTemplate(ctx context.Context, arg CreateDeploymentTemplateParams) (DeploymentTemplate, error)
	CreatePlatformEvent(ctx context.Context, arg CreatePlatformEventParams) (PlatformEvent, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// Record that the agent owning this resource has gone offline. It writes a
	// condition and health only — agent_id is deliberately UNTOUCHED: in docker mode
	// there is no scheduler to reschedule onto and the workload's data may be
	// host-local, so silently reassigning it would risk a split brain (two hosts
	// running the same stateful workload) the moment the original host came back.
	// Surface it, escalate it, let a human or an explicit policy decide.
	//
	// The COALESCE guard makes it idempotent: the supervisor re-runs every interval,
	// and re-stamping would churn updated_at (which orders the work feed) and defeat
	// once-per-episode escalation. No matching row means "already flagged".
	// The flag clears on its own, because the next real agent report REPLACES status
	// wholesale (see ApplyAgentReport) — recovery needs no separate unflag path.
	FlagResourceHostUnreachable(ctx context.Context, resourceUuid uuid.UUID) (Resource, error)
	GetAgentByID(ctx context.Context, agentID int64) (Agent, error)
	GetAgentByUUID(ctx context.Context, agentUuid uuid.UUID) (Agent, error)
	GetControlPlane(ctx context.Context) (ControlPlane, error)
	GetDeploymentTemplate(ctx context.Context, arg GetDeploymentTemplateParams) (DeploymentTemplate, error)
	GetProjectByID(ctx context.Context, projectID int64) (Project, error)
	GetProjectByTenantAndName(ctx context.Context, arg GetProjectByTenantAndNameParams) (Project, error)
	GetProjectByUUID(ctx context.Context, projectUuid uuid.UUID) (Project, error)
	GetProviderByID(ctx context.Context, providerID int64) (Provider, error)
	GetProviderByUUID(ctx context.Context, providerUuid uuid.UUID) (Provider, error)
	GetResourceByID(ctx context.Context, resourceID int64) (Resource, error)
	GetResourceByUUID(ctx context.Context, resourceUuid uuid.UUID) (Resource, error)
	GetServiceByID(ctx context.Context, serviceID int64) (Service, error)
	GetServiceByTenantAndName(ctx context.Context, arg GetServiceByTenantAndNameParams) (Service, error)
	GetServiceByUUID(ctx context.Context, serviceUuid uuid.UUID) (Service, error)
	// The platform's root tenant — the single required system tenant.
	GetSystemTenant(ctx context.Context) (Tenant, error)
	GetTenantByID(ctx context.Context, tenantID int64) (Tenant, error)
	GetTenantByName(ctx context.Context, name string) (Tenant, error)
	GetTenantByUUID(ctx context.Context, tenantUuid uuid.UUID) (Tenant, error)
	ListAgentsByTenant(ctx context.Context, arg ListAgentsByTenantParams) ([]Agent, error)
	ListDeploymentTemplates(ctx context.Context, arg ListDeploymentTemplatesParams) ([]DeploymentTemplate, error)
	// Every agent CURRENTLY considered offline, not just the ones this sweep
	// transitioned. Supervision needs the standing set: a workload assigned to a
	// host that died three ticks ago is still stranded, and a resource created or
	// reassigned after the transition would otherwise never be noticed.
	ListOfflineAgents(ctx context.Context) ([]Agent, error)
	// The reconciler's work feed (read-only variant; the gateway uses ClaimAgentWork
	// which additionally stamps the lease + agent assignment). A row is fed when:
	//   * its observed state lags its spec, OR it is being torn down ('deleting'),
	//     OR a prior attempt failed retryably ('error');
	//   * it is not parked as 'failed' (budget exhausted — only a spec change
	//     re-arms it);
	//   * no dispatch lease is active and any retry backoff has elapsed.
	ListOutOfSyncResources(ctx context.Context, limit int32) ([]Resource, error)
	// Newest first: an operator reading the escalation log wants the current
	// incident, not the install's first boot.
	ListPlatformEvents(ctx context.Context, arg ListPlatformEventsParams) ([]PlatformEvent, error)
	// The incident timeline for one agent/resource/service.
	ListPlatformEventsBySubject(ctx context.Context, arg ListPlatformEventsBySubjectParams) ([]PlatformEvent, error)
	ListProjectsByTenant(ctx context.Context, arg ListProjectsByTenantParams) ([]Project, error)
	ListProvidersByKind(ctx context.Context, arg ListProvidersByKindParams) ([]Provider, error)
	ListProvidersByTenant(ctx context.Context, arg ListProvidersByTenantParams) ([]Provider, error)
	ListResourcesByProject(ctx context.Context, arg ListResourcesByProjectParams) ([]Resource, error)
	ListResourcesByTenant(ctx context.Context, arg ListResourcesByTenantParams) ([]Resource, error)
	ListServicesByTenant(ctx context.Context, arg ListServicesByTenantParams) ([]Service, error)
	// The platform's system services — the ones Core must keep running at all times.
	ListSystemServices(ctx context.Context) ([]Service, error)
	// Every system-tier instance, across all tenants and projects — the supervisor's
	// feed. Availability tier is a REGISTRATION property carried in metadata
	// (12-supervision-and-availability.md), never inferred from kind or name: the
	// same image is a must-never-go-down platform component when registered as
	// system and a disposable tenant workload when it is not.
	//
	// Unlike the reconciler feed this applies NO lease/backoff/state gates: the
	// supervisor's whole job is to look at rows the feed has given up on (parked
	// 'failed', leased to a dead agent) and decide they must run anyway.
	ListSystemTierResources(ctx context.Context) ([]Resource, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	MarkAgentEnrolled(ctx context.Context, arg MarkAgentEnrolledParams) (Agent, error)
	// Deletion is a desired-state change, not an immediate erase: the row flips to
	// state='deleting' but keeps deleted_at NULL so it stays IN the work feed and
	// PullWork ships it to its agent as a teardown envelope. Only the agent's
	// "removed" report finalizes the delete (ApplyAgentReport with finalize) —
	// otherwise the workload would keep running on the host with no record of it.
	MarkResourceDeleting(ctx context.Context, resourceUuid uuid.UUID) error
	// The liveness sweeper. An agent that stopped beating is a host that may be
	// gone, and until something writes that down every agent looks online forever
	// (last_seen_at was previously written and read by nothing).
	//
	// Scope is deliberately narrow:
	//   * status <> 'offline' — only TRANSITIONS are returned, which is what makes
	//     the caller's "emit one escalation per episode" free instead of requiring
	//     de-duplication state.
	//   * last_seen_at IS NOT NULL — an agent that has never checked in was never
	//     online, so calling it 'offline' would overwrite the more precise truth
	//     ('pending': created but not yet enrolled/registered).
	MarkStaleAgentsOffline(ctx context.Context, staleSeconds float64) ([]Agent, error)
	// Force a system-tier instance back onto the work feed.
	//
	// Bumping generation is what re-arms the EXISTING feed (observed_generation now
	// lags again) rather than inventing a second dispatch path; clearing
	// leased_until releases a lease held by an agent that will never answer; and
	// resetting attempts/next_attempt_at is the load-bearing part: the retry budget
	// exists to stop a poisoned TENANT spec from hot-looping an agent, but a system
	// service may never be parked as terminally 'failed' — "never goes down"
	// outranks "stop wasting cycles". System-tier work is therefore retried forever,
	// with the supervisor's interval as the backoff and an escalation record once a
	// human is needed.
	//
	// The state guard is not optional: 'deleting' is an operator-requested teardown,
	// a DESIRED state, and resurrecting it would turn keep-alive into a service that
	// cannot be removed. A COMPLETED teardown needs no guard — it stamps deleted_at,
	// which the WHERE clause already excludes. State 'removed' with deleted_at still
	// NULL therefore means the workload vanished without anyone asking, which is a
	// re-dispatch case rather than an exempt one.
	RedispatchSystemResource(ctx context.Context, resourceUuid uuid.UUID) (Resource, error)
	SoftDeleteAgent(ctx context.Context, agentUuid uuid.UUID) error
	SoftDeleteDeploymentTemplate(ctx context.Context, arg SoftDeleteDeploymentTemplateParams) error
	SoftDeleteProject(ctx context.Context, projectUuid uuid.UUID) error
	SoftDeleteProvider(ctx context.Context, providerUuid uuid.UUID) error
	SoftDeleteService(ctx context.Context, serviceUuid uuid.UUID) error
	SoftDeleteTenant(ctx context.Context, tenantUuid uuid.UUID) error
	UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (Agent, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error)
	// A spec change bumps generation and re-arms the reconciler (state -> pending).
	// It also resets the retry budget (attempts/next_attempt_at): a resource parked
	// as 'failed' after exhausting its budget gets a fresh budget only when its
	// desired state actually changes — never by the failing spec being retried
	// forever on its own.
	UpdateResourceSpec(ctx context.Context, arg UpdateResourceSpecParams) (Resource, error)
	// The reconciler writes observed state back, marking how far it has caught up.
	UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (Resource, error)
	UpdateServiceStatus(ctx context.Context, arg UpdateServiceStatusParams) (Service, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpsertControlPlane(ctx context.Context, arg UpsertControlPlaneParams) (ControlPlane, error)
}

var _ Querier = (*Queries)(nil)
