// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AgentHeartbeat(ctx context.Context, agentUuid uuid.UUID) (Agent, error)
	AssignResourceAgent(ctx context.Context, arg AssignResourceAgentParams) (Resource, error)
	CountAgentsByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountProjectsByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountProvidersByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountResourcesByProject(ctx context.Context, projectID int64) (int64, error)
	CountServicesByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountTenants(ctx context.Context) (int64, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	GetAgentByID(ctx context.Context, agentID int64) (Agent, error)
	GetAgentByUUID(ctx context.Context, agentUuid uuid.UUID) (Agent, error)
	GetProjectByID(ctx context.Context, projectID int64) (Project, error)
	GetProjectByUUID(ctx context.Context, projectUuid uuid.UUID) (Project, error)
	GetProviderByID(ctx context.Context, providerID int64) (Provider, error)
	GetProviderByUUID(ctx context.Context, providerUuid uuid.UUID) (Provider, error)
	GetResourceByID(ctx context.Context, resourceID int64) (Resource, error)
	GetResourceByUUID(ctx context.Context, resourceUuid uuid.UUID) (Resource, error)
	GetServiceByID(ctx context.Context, serviceID int64) (Service, error)
	GetServiceByTenantAndName(ctx context.Context, arg GetServiceByTenantAndNameParams) (Service, error)
	GetServiceByUUID(ctx context.Context, serviceUuid uuid.UUID) (Service, error)
	// The platform's root tenant — the single required system tenant.
	GetSystemTenant(ctx context.Context) (Tenant, error)
	GetTenantByID(ctx context.Context, tenantID int64) (Tenant, error)
	GetTenantByName(ctx context.Context, name string) (Tenant, error)
	GetTenantByUUID(ctx context.Context, tenantUuid uuid.UUID) (Tenant, error)
	ListAgentsByTenant(ctx context.Context, arg ListAgentsByTenantParams) ([]Agent, error)
	// The reconciler's work feed: resources whose observed state lags their spec.
	ListOutOfSyncResources(ctx context.Context, limit int32) ([]Resource, error)
	ListProjectsByTenant(ctx context.Context, arg ListProjectsByTenantParams) ([]Project, error)
	ListProvidersByKind(ctx context.Context, arg ListProvidersByKindParams) ([]Provider, error)
	ListProvidersByTenant(ctx context.Context, arg ListProvidersByTenantParams) ([]Provider, error)
	ListResourcesByProject(ctx context.Context, arg ListResourcesByProjectParams) ([]Resource, error)
	ListResourcesByTenant(ctx context.Context, arg ListResourcesByTenantParams) ([]Resource, error)
	ListServicesByTenant(ctx context.Context, arg ListServicesByTenantParams) ([]Service, error)
	// The platform's system services — the ones Core must keep running at all times.
	ListSystemServices(ctx context.Context) ([]Service, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	SoftDeleteAgent(ctx context.Context, agentUuid uuid.UUID) error
	SoftDeleteProject(ctx context.Context, projectUuid uuid.UUID) error
	SoftDeleteProvider(ctx context.Context, providerUuid uuid.UUID) error
	// Deletion is a desired-state change too: mark deleting so the reconciler can tear down.
	SoftDeleteResource(ctx context.Context, resourceUuid uuid.UUID) error
	SoftDeleteService(ctx context.Context, serviceUuid uuid.UUID) error
	SoftDeleteTenant(ctx context.Context, tenantUuid uuid.UUID) error
	UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (Agent, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error)
	// A spec change bumps generation and re-arms the reconciler (state -> pending).
	UpdateResourceSpec(ctx context.Context, arg UpdateResourceSpecParams) (Resource, error)
	// The reconciler writes observed state back, marking how far it has caught up.
	UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (Resource, error)
	UpdateServiceStatus(ctx context.Context, arg UpdateServiceStatusParams) (Service, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
}

var _ Querier = (*Queries)(nil)
