// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyAgentReport = `-- name: ApplyAgentReport :one
UPDATE resources
SET status = $2,
    state = $3,
    observed_generation = GREATEST(observed_generation, $4),
    attempts = $5,
    next_attempt_at = $6,
    leased_until = NULL,
    deleted_at = CASE WHEN $7::bool THEN now() ELSE deleted_at END,
    updated_at = now()
WHERE resource_uuid = $1 AND deleted_at IS NULL
RETURNING resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_type, mrn_resource_path, kind, name, state, spec, status, generation, observed_generation, leased_until, attempts, next_attempt_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type ApplyAgentReportParams struct {
	ResourceUuid       uuid.UUID          `json:"resource_uuid"`
	Status             []byte             `json:"status"`
	State              string             `json:"state"`
	ObservedGeneration int64              `json:"observed_generation"`
	Attempts           int32              `json:"attempts"`
	NextAttemptAt      pgtype.Timestamptz `json:"next_attempt_at"`
	Finalize           bool               `json:"finalize"`
}

// The gateway's single write path for agent status reports. The service layer
// computes the resulting state / attempts / backoff in Go; this statement
// applies them atomically and ALWAYS releases the dispatch lease (a report is
// the agent's answer for the leased item). observed_generation only moves
// forward (GREATEST) so a stale drift report can never rewind convergence
// progress; failure paths pass 0 to leave it untouched. `finalize` stamps
// deleted_at — the terminal step of the teardown protocol after an agent
// reports the workload removed.
func (q *Queries) ApplyAgentReport(ctx context.Context, arg ApplyAgentReportParams) (Resource, error) {
	row := q.db.QueryRow(ctx, applyAgentReport,
		arg.ResourceUuid,
		arg.Status,
		arg.State,
		arg.ObservedGeneration,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.Finalize,
	)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.ResourceUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.ProviderID,
		&i.AgentID,
		&i.OwnerResourceID,
		&i.MrnService,
		&i.MrnTenant,
		&i.MrnProject,
		&i.MrnResourceType,
		&i.MrnResourcePath,
		&i.Kind,
		&i.Name,
		&i.State,
		&i.Spec,
		&i.Status,
		&i.Generation,
		&i.ObservedGeneration,
		&i.LeasedUntil,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const assignResourceAgent = `-- name: AssignResourceAgent :one
UPDATE resources
SET agent_id = $2, updated_at = now()
WHERE resource_uuid = $1 AND deleted_at IS NULL
RETURNING resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_type, mrn_resource_path, kind, name, state, spec, status, generation, observed_generation, leased_until, attempts, next_attempt_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type AssignResourceAgentParams struct {
	ResourceUuid uuid.UUID   `json:"resource_uuid"`
	AgentID      pgtype.Int8 `json:"agent_id"`
}

func (q *Queries) AssignResourceAgent(ctx context.Context, arg AssignResourceAgentParams) (Resource, error) {
	row := q.db.QueryRow(ctx, assignResourceAgent, arg.ResourceUuid, arg.AgentID)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.ResourceUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.ProviderID,
		&i.AgentID,
		&i.OwnerResourceID,
		&i.MrnService,
		&i.MrnTenant,
		&i.MrnProject,
		&i.MrnResourceType,
		&i.MrnResourcePath,
		&i.Kind,
		&i.Name,
		&i.State,
		&i.Spec,
		&i.Status,
		&i.Generation,
		&i.ObservedGeneration,
		&i.LeasedUntil,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const claimAgentWork = `-- name: ClaimAgentWork :many
UPDATE resources
SET agent_id = $1,
    leased_until = now() + make_interval(secs => $2::float8),
    updated_at = now()
WHERE resource_id IN (
    SELECT r.resource_id FROM resources r
    WHERE (r.observed_generation < r.generation OR r.state IN ('deleting', 'error'))
      AND r.state <> 'failed'
      AND r.deleted_at IS NULL
      AND (r.agent_id = $1 OR r.agent_id IS NULL)
      AND (r.leased_until IS NULL OR r.leased_until < now())
      AND (r.next_attempt_at IS NULL OR r.next_attempt_at <= now())
    ORDER BY r.updated_at ASC
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_type, mrn_resource_path, kind, name, state, spec, status, generation, observed_generation, leased_until, attempts, next_attempt_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type ClaimAgentWorkParams struct {
	AgentID      pgtype.Int8 `json:"agent_id"`
	LeaseSeconds float64     `json:"lease_seconds"`
	MaxItems     int32       `json:"max_items"`
}

// PullWork's atomic claim. Feed rules match ListOutOfSyncResources, scoped to
// items already assigned to the calling agent OR unassigned (first claim is
// sticky: agent_id is stamped and later pulls by other agents skip the row).
// The FOR UPDATE SKIP LOCKED subselect + single UPDATE make it impossible for
// two concurrent agents to claim the same item; the lease keeps the item out
// of the feed until it expires or a status report releases it.
func (q *Queries) ClaimAgentWork(ctx context.Context, arg ClaimAgentWorkParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, claimAgentWork, arg.AgentID, arg.LeaseSeconds, arg.MaxItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ResourceID,
			&i.ResourceUuid,
			&i.TenantID,
			&i.ProjectID,
			&i.ProviderID,
			&i.AgentID,
			&i.OwnerResourceID,
			&i.MrnService,
			&i.MrnTenant,
			&i.MrnProject,
			&i.MrnResourceType,
			&i.MrnResourcePath,
			&i.Kind,
			&i.Name,
			&i.State,
			&i.Spec,
			&i.Status,
			&i.Generation,
			&i.ObservedGeneration,
			&i.LeasedUntil,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.Metadata,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countResourcesByProject = `-- name: CountResourcesByProject :one
SELECT count(*) FROM resources WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountResourcesByProject(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countResourcesByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResource = `-- name: CreateResource :one
INSERT INTO resources (
    tenant_id, project_id, provider_id, agent_id, owner_resource_id,
    mrn_service, mrn_tenant, mrn_project, mrn_resource_type, mrn_resource_path,
    kind, name, spec, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_type, mrn_resource_path, kind, name, state, spec, status, generation, observed_generation, leased_until, attempts, next_attempt_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateResourceParams struct {
	TenantID        int64       `json:"tenant_id"`
	ProjectID       int64       `json:"project_id"`
	ProviderID      pgtype.Int8 `json:"provider_id"`
	AgentID         pgtype.Int8 `json:"agent_id"`
	OwnerResourceID pgtype.Int8 `json:"owner_resource_id"`
	MrnService      string      `json:"mrn_service"`
	MrnTenant       string      `json:"mrn_tenant"`
	MrnProject      string      `json:"mrn_project"`
	MrnResourceType string      `json:"mrn_resource_type"`
	MrnResourcePath string      `json:"mrn_resource_path"`
	Kind            string      `json:"kind"`
	Name            string      `json:"name"`
	Spec            []byte      `json:"spec"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.TenantID,
		arg.ProjectID,
		arg.ProviderID,
		arg.AgentID,
		arg.OwnerResourceID,
		arg.MrnService,
		arg.MrnTenant,
		arg.MrnProject,
		arg.MrnResourceType,
		arg.MrnResourcePath,
		arg.Kind,
		arg.Name,
		arg.Spec,
		arg.Metadata,
	)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.ResourceUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.ProviderID,
		&i.AgentID,
		&i.OwnerResourceID,
		&i.MrnService,
		&i.MrnTenant,
		&i.MrnProject,
		&i.MrnResourceType,
		&i.MrnResourcePath,
		&i.Kind,
		&i.Name,
		&i.State,
		&i.Spec,
		&i.Status,
		&i.Generation,
		&i.ObservedGeneration,
		&i.LeasedUntil,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getResourceByID = `-- name: GetResourceByID :one
SELECT resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_type, mrn_resource_path, kind, name, state, spec, status, generation, observed_generation, leased_until, attempts, next_attempt_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM resources WHERE resource_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetResourceByID(ctx context.Context, resourceID int64) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceByID, resourceID)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.ResourceUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.ProviderID,
		&i.AgentID,
		&i.OwnerResourceID,
		&i.MrnService,
		&i.MrnTenant,
		&i.MrnProject,
		&i.MrnResourceType,
		&i.MrnResourcePath,
		&i.Kind,
		&i.Name,
		&i.State,
		&i.Spec,
		&i.Status,
		&i.Generation,
		&i.ObservedGeneration,
		&i.LeasedUntil,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getResourceByUUID = `-- name: GetResourceByUUID :one
SELECT resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_type, mrn_resource_path, kind, name, state, spec, status, generation, observed_generation, leased_until, attempts, next_attempt_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM resources WHERE resource_uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetResourceByUUID(ctx context.Context, resourceUuid uuid.UUID) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceByUUID, resourceUuid)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.ResourceUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.ProviderID,
		&i.AgentID,
		&i.OwnerResourceID,
		&i.MrnService,
		&i.MrnTenant,
		&i.MrnProject,
		&i.MrnResourceType,
		&i.MrnResourcePath,
		&i.Kind,
		&i.Name,
		&i.State,
		&i.Spec,
		&i.Status,
		&i.Generation,
		&i.ObservedGeneration,
		&i.LeasedUntil,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOutOfSyncResources = `-- name: ListOutOfSyncResources :many
SELECT resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_type, mrn_resource_path, kind, name, state, spec, status, generation, observed_generation, leased_until, attempts, next_attempt_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM resources
WHERE (observed_generation < generation OR state IN ('deleting', 'error'))
  AND state <> 'failed'
  AND deleted_at IS NULL
  AND (leased_until IS NULL OR leased_until < now())
  AND (next_attempt_at IS NULL OR next_attempt_at <= now())
ORDER BY updated_at ASC
LIMIT $1
`

// The reconciler's work feed (read-only variant; the gateway uses ClaimAgentWork
// which additionally stamps the lease + agent assignment). A row is fed when:
//   - its observed state lags its spec, OR it is being torn down ('deleting'),
//     OR a prior attempt failed retryably ('error');
//   - it is not parked as 'failed' (budget exhausted — only a spec change
//     re-arms it);
//   - no dispatch lease is active and any retry backoff has elapsed.
func (q *Queries) ListOutOfSyncResources(ctx context.Context, limit int32) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listOutOfSyncResources, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ResourceID,
			&i.ResourceUuid,
			&i.TenantID,
			&i.ProjectID,
			&i.ProviderID,
			&i.AgentID,
			&i.OwnerResourceID,
			&i.MrnService,
			&i.MrnTenant,
			&i.MrnProject,
			&i.MrnResourceType,
			&i.MrnResourcePath,
			&i.Kind,
			&i.Name,
			&i.State,
			&i.Spec,
			&i.Status,
			&i.Generation,
			&i.ObservedGeneration,
			&i.LeasedUntil,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.Metadata,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByProject = `-- name: ListResourcesByProject :many
SELECT resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_type, mrn_resource_path, kind, name, state, spec, status, generation, observed_generation, leased_until, attempts, next_attempt_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM resources
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListResourcesByProjectParams struct {
	ProjectID int64 `json:"project_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListResourcesByProject(ctx context.Context, arg ListResourcesByProjectParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ResourceID,
			&i.ResourceUuid,
			&i.TenantID,
			&i.ProjectID,
			&i.ProviderID,
			&i.AgentID,
			&i.OwnerResourceID,
			&i.MrnService,
			&i.MrnTenant,
			&i.MrnProject,
			&i.MrnResourceType,
			&i.MrnResourcePath,
			&i.Kind,
			&i.Name,
			&i.State,
			&i.Spec,
			&i.Status,
			&i.Generation,
			&i.ObservedGeneration,
			&i.LeasedUntil,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.Metadata,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByTenant = `-- name: ListResourcesByTenant :many
SELECT resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_type, mrn_resource_path, kind, name, state, spec, status, generation, observed_generation, leased_until, attempts, next_attempt_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM resources
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListResourcesByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListResourcesByTenant(ctx context.Context, arg ListResourcesByTenantParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ResourceID,
			&i.ResourceUuid,
			&i.TenantID,
			&i.ProjectID,
			&i.ProviderID,
			&i.AgentID,
			&i.OwnerResourceID,
			&i.MrnService,
			&i.MrnTenant,
			&i.MrnProject,
			&i.MrnResourceType,
			&i.MrnResourcePath,
			&i.Kind,
			&i.Name,
			&i.State,
			&i.Spec,
			&i.Status,
			&i.Generation,
			&i.ObservedGeneration,
			&i.LeasedUntil,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.Metadata,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markResourceDeleting = `-- name: MarkResourceDeleting :exec
UPDATE resources SET state = 'deleting', updated_at = now()
WHERE resource_uuid = $1 AND deleted_at IS NULL
`

// Deletion is a desired-state change, not an immediate erase: the row flips to
// state='deleting' but keeps deleted_at NULL so it stays IN the work feed and
// PullWork ships it to its agent as a teardown envelope. Only the agent's
// "removed" report finalizes the delete (ApplyAgentReport with finalize) —
// otherwise the workload would keep running on the host with no record of it.
func (q *Queries) MarkResourceDeleting(ctx context.Context, resourceUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, markResourceDeleting, resourceUuid)
	return err
}

const updateResourceSpec = `-- name: UpdateResourceSpec :one
UPDATE resources
SET spec = $2, metadata = $3,
    mrn_service = $4, mrn_tenant = $5, mrn_project = $6, mrn_resource_type = $7, mrn_resource_path = $8,
    generation = generation + 1, state = 'pending',
    attempts = 0, next_attempt_at = NULL, updated_at = now()
WHERE resource_uuid = $1 AND deleted_at IS NULL
RETURNING resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_type, mrn_resource_path, kind, name, state, spec, status, generation, observed_generation, leased_until, attempts, next_attempt_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateResourceSpecParams struct {
	ResourceUuid    uuid.UUID `json:"resource_uuid"`
	Spec            []byte    `json:"spec"`
	Metadata        []byte    `json:"metadata"`
	MrnService      string    `json:"mrn_service"`
	MrnTenant       string    `json:"mrn_tenant"`
	MrnProject      string    `json:"mrn_project"`
	MrnResourceType string    `json:"mrn_resource_type"`
	MrnResourcePath string    `json:"mrn_resource_path"`
}

// A spec change bumps generation and re-arms the reconciler (state -> pending).
// It also resets the retry budget (attempts/next_attempt_at): a resource parked
// as 'failed' after exhausting its budget gets a fresh budget only when its
// desired state actually changes — never by the failing spec being retried
// forever on its own.
func (q *Queries) UpdateResourceSpec(ctx context.Context, arg UpdateResourceSpecParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResourceSpec,
		arg.ResourceUuid,
		arg.Spec,
		arg.Metadata,
		arg.MrnService,
		arg.MrnTenant,
		arg.MrnProject,
		arg.MrnResourceType,
		arg.MrnResourcePath,
	)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.ResourceUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.ProviderID,
		&i.AgentID,
		&i.OwnerResourceID,
		&i.MrnService,
		&i.MrnTenant,
		&i.MrnProject,
		&i.MrnResourceType,
		&i.MrnResourcePath,
		&i.Kind,
		&i.Name,
		&i.State,
		&i.Spec,
		&i.Status,
		&i.Generation,
		&i.ObservedGeneration,
		&i.LeasedUntil,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateResourceStatus = `-- name: UpdateResourceStatus :one
UPDATE resources
SET status = $2, state = $3, observed_generation = $4, updated_at = now()
WHERE resource_uuid = $1 AND deleted_at IS NULL
RETURNING resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, mrn_service, mrn_tenant, mrn_project, mrn_resource_type, mrn_resource_path, kind, name, state, spec, status, generation, observed_generation, leased_until, attempts, next_attempt_at, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateResourceStatusParams struct {
	ResourceUuid       uuid.UUID `json:"resource_uuid"`
	Status             []byte    `json:"status"`
	State              string    `json:"state"`
	ObservedGeneration int64     `json:"observed_generation"`
}

// The reconciler writes observed state back, marking how far it has caught up.
func (q *Queries) UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResourceStatus,
		arg.ResourceUuid,
		arg.Status,
		arg.State,
		arg.ObservedGeneration,
	)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.ResourceUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.ProviderID,
		&i.AgentID,
		&i.OwnerResourceID,
		&i.MrnService,
		&i.MrnTenant,
		&i.MrnProject,
		&i.MrnResourceType,
		&i.MrnResourcePath,
		&i.Kind,
		&i.Name,
		&i.State,
		&i.Spec,
		&i.Status,
		&i.Generation,
		&i.ObservedGeneration,
		&i.LeasedUntil,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
