// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignResourceAgent = `-- name: AssignResourceAgent :one
UPDATE resources
SET agent_id = $2, updated_at = now()
WHERE resource_uuid = $1 AND deleted_at IS NULL
RETURNING resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, kind, name, state, spec, status, generation, observed_generation, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type AssignResourceAgentParams struct {
	ResourceUuid uuid.UUID   `json:"resource_uuid"`
	AgentID      pgtype.Int8 `json:"agent_id"`
}

func (q *Queries) AssignResourceAgent(ctx context.Context, arg AssignResourceAgentParams) (Resource, error) {
	row := q.db.QueryRow(ctx, assignResourceAgent, arg.ResourceUuid, arg.AgentID)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.ResourceUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.ProviderID,
		&i.AgentID,
		&i.OwnerResourceID,
		&i.Kind,
		&i.Name,
		&i.State,
		&i.Spec,
		&i.Status,
		&i.Generation,
		&i.ObservedGeneration,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countResourcesByProject = `-- name: CountResourcesByProject :one
SELECT count(*) FROM resources WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountResourcesByProject(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countResourcesByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResource = `-- name: CreateResource :one
INSERT INTO resources (tenant_id, project_id, provider_id, agent_id, owner_resource_id, kind, name, spec, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, kind, name, state, spec, status, generation, observed_generation, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateResourceParams struct {
	TenantID        int64       `json:"tenant_id"`
	ProjectID       int64       `json:"project_id"`
	ProviderID      pgtype.Int8 `json:"provider_id"`
	AgentID         pgtype.Int8 `json:"agent_id"`
	OwnerResourceID pgtype.Int8 `json:"owner_resource_id"`
	Kind            string      `json:"kind"`
	Name            string      `json:"name"`
	Spec            []byte      `json:"spec"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.TenantID,
		arg.ProjectID,
		arg.ProviderID,
		arg.AgentID,
		arg.OwnerResourceID,
		arg.Kind,
		arg.Name,
		arg.Spec,
		arg.Metadata,
	)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.ResourceUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.ProviderID,
		&i.AgentID,
		&i.OwnerResourceID,
		&i.Kind,
		&i.Name,
		&i.State,
		&i.Spec,
		&i.Status,
		&i.Generation,
		&i.ObservedGeneration,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getResourceByID = `-- name: GetResourceByID :one
SELECT resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, kind, name, state, spec, status, generation, observed_generation, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM resources WHERE resource_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetResourceByID(ctx context.Context, resourceID int64) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceByID, resourceID)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.ResourceUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.ProviderID,
		&i.AgentID,
		&i.OwnerResourceID,
		&i.Kind,
		&i.Name,
		&i.State,
		&i.Spec,
		&i.Status,
		&i.Generation,
		&i.ObservedGeneration,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getResourceByUUID = `-- name: GetResourceByUUID :one
SELECT resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, kind, name, state, spec, status, generation, observed_generation, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM resources WHERE resource_uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetResourceByUUID(ctx context.Context, resourceUuid uuid.UUID) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceByUUID, resourceUuid)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.ResourceUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.ProviderID,
		&i.AgentID,
		&i.OwnerResourceID,
		&i.Kind,
		&i.Name,
		&i.State,
		&i.Spec,
		&i.Status,
		&i.Generation,
		&i.ObservedGeneration,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOutOfSyncResources = `-- name: ListOutOfSyncResources :many
SELECT resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, kind, name, state, spec, status, generation, observed_generation, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM resources
WHERE observed_generation < generation AND state <> 'failed' AND deleted_at IS NULL
ORDER BY updated_at ASC
LIMIT $1
`

// The reconciler's work feed: resources whose observed state lags their spec.
func (q *Queries) ListOutOfSyncResources(ctx context.Context, limit int32) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listOutOfSyncResources, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ResourceID,
			&i.ResourceUuid,
			&i.TenantID,
			&i.ProjectID,
			&i.ProviderID,
			&i.AgentID,
			&i.OwnerResourceID,
			&i.Kind,
			&i.Name,
			&i.State,
			&i.Spec,
			&i.Status,
			&i.Generation,
			&i.ObservedGeneration,
			&i.Metadata,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByProject = `-- name: ListResourcesByProject :many
SELECT resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, kind, name, state, spec, status, generation, observed_generation, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM resources
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListResourcesByProjectParams struct {
	ProjectID int64 `json:"project_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListResourcesByProject(ctx context.Context, arg ListResourcesByProjectParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ResourceID,
			&i.ResourceUuid,
			&i.TenantID,
			&i.ProjectID,
			&i.ProviderID,
			&i.AgentID,
			&i.OwnerResourceID,
			&i.Kind,
			&i.Name,
			&i.State,
			&i.Spec,
			&i.Status,
			&i.Generation,
			&i.ObservedGeneration,
			&i.Metadata,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByTenant = `-- name: ListResourcesByTenant :many
SELECT resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, kind, name, state, spec, status, generation, observed_generation, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM resources
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListResourcesByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListResourcesByTenant(ctx context.Context, arg ListResourcesByTenantParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ResourceID,
			&i.ResourceUuid,
			&i.TenantID,
			&i.ProjectID,
			&i.ProviderID,
			&i.AgentID,
			&i.OwnerResourceID,
			&i.Kind,
			&i.Name,
			&i.State,
			&i.Spec,
			&i.Status,
			&i.Generation,
			&i.ObservedGeneration,
			&i.Metadata,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteResource = `-- name: SoftDeleteResource :exec
UPDATE resources SET state = 'deleting', deleted_at = now(), updated_at = now()
WHERE resource_uuid = $1 AND deleted_at IS NULL
`

// Deletion is a desired-state change too: mark deleting so the reconciler can tear down.
func (q *Queries) SoftDeleteResource(ctx context.Context, resourceUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteResource, resourceUuid)
	return err
}

const updateResourceSpec = `-- name: UpdateResourceSpec :one
UPDATE resources
SET spec = $2, metadata = $3, generation = generation + 1, state = 'pending', updated_at = now()
WHERE resource_uuid = $1 AND deleted_at IS NULL
RETURNING resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, kind, name, state, spec, status, generation, observed_generation, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateResourceSpecParams struct {
	ResourceUuid uuid.UUID `json:"resource_uuid"`
	Spec         []byte    `json:"spec"`
	Metadata     []byte    `json:"metadata"`
}

// A spec change bumps generation and re-arms the reconciler (state -> pending).
func (q *Queries) UpdateResourceSpec(ctx context.Context, arg UpdateResourceSpecParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResourceSpec, arg.ResourceUuid, arg.Spec, arg.Metadata)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.ResourceUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.ProviderID,
		&i.AgentID,
		&i.OwnerResourceID,
		&i.Kind,
		&i.Name,
		&i.State,
		&i.Spec,
		&i.Status,
		&i.Generation,
		&i.ObservedGeneration,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateResourceStatus = `-- name: UpdateResourceStatus :one
UPDATE resources
SET status = $2, state = $3, observed_generation = $4, updated_at = now()
WHERE resource_uuid = $1 AND deleted_at IS NULL
RETURNING resource_id, resource_uuid, tenant_id, project_id, provider_id, agent_id, owner_resource_id, kind, name, state, spec, status, generation, observed_generation, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateResourceStatusParams struct {
	ResourceUuid       uuid.UUID `json:"resource_uuid"`
	Status             []byte    `json:"status"`
	State              string    `json:"state"`
	ObservedGeneration int64     `json:"observed_generation"`
}

// The reconciler writes observed state back, marking how far it has caught up.
func (q *Queries) UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResourceStatus,
		arg.ResourceUuid,
		arg.Status,
		arg.State,
		arg.ObservedGeneration,
	)
	var i Resource
	err := row.Scan(
		&i.ResourceID,
		&i.ResourceUuid,
		&i.TenantID,
		&i.ProjectID,
		&i.ProviderID,
		&i.AgentID,
		&i.OwnerResourceID,
		&i.Kind,
		&i.Name,
		&i.State,
		&i.Spec,
		&i.Status,
		&i.Generation,
		&i.ObservedGeneration,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
