// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countServicesByTenant = `-- name: CountServicesByTenant :one
SELECT count(*) FROM services
WHERE tenant_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountServicesByTenant(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countServicesByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (tenant_id, name, kind, status, endpoint, version, metadata, registered_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING service_id, service_uuid, tenant_id, name, kind, status, endpoint, version, metadata, registered_at, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateServiceParams struct {
	TenantID     int64              `json:"tenant_id"`
	Name         string             `json:"name"`
	Kind         string             `json:"kind"`
	Status       string             `json:"status"`
	Endpoint     string             `json:"endpoint"`
	Version      string             `json:"version"`
	Metadata     []byte             `json:"metadata"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.TenantID,
		arg.Name,
		arg.Kind,
		arg.Status,
		arg.Endpoint,
		arg.Version,
		arg.Metadata,
		arg.RegisteredAt,
	)
	var i Service
	err := row.Scan(
		&i.ServiceID,
		&i.ServiceUuid,
		&i.TenantID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.Endpoint,
		&i.Version,
		&i.Metadata,
		&i.RegisteredAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT service_id, service_uuid, tenant_id, name, kind, status, endpoint, version, metadata, registered_at, created_by, updated_by, created_at, updated_at, deleted_at FROM services
WHERE service_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetServiceByID(ctx context.Context, serviceID int64) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, serviceID)
	var i Service
	err := row.Scan(
		&i.ServiceID,
		&i.ServiceUuid,
		&i.TenantID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.Endpoint,
		&i.Version,
		&i.Metadata,
		&i.RegisteredAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getServiceByTenantAndName = `-- name: GetServiceByTenantAndName :one
SELECT service_id, service_uuid, tenant_id, name, kind, status, endpoint, version, metadata, registered_at, created_by, updated_by, created_at, updated_at, deleted_at FROM services
WHERE tenant_id = $1 AND name = $2 AND deleted_at IS NULL
`

type GetServiceByTenantAndNameParams struct {
	TenantID int64  `json:"tenant_id"`
	Name     string `json:"name"`
}

func (q *Queries) GetServiceByTenantAndName(ctx context.Context, arg GetServiceByTenantAndNameParams) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByTenantAndName, arg.TenantID, arg.Name)
	var i Service
	err := row.Scan(
		&i.ServiceID,
		&i.ServiceUuid,
		&i.TenantID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.Endpoint,
		&i.Version,
		&i.Metadata,
		&i.RegisteredAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getServiceByUUID = `-- name: GetServiceByUUID :one
SELECT service_id, service_uuid, tenant_id, name, kind, status, endpoint, version, metadata, registered_at, created_by, updated_by, created_at, updated_at, deleted_at FROM services
WHERE service_uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetServiceByUUID(ctx context.Context, serviceUuid uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByUUID, serviceUuid)
	var i Service
	err := row.Scan(
		&i.ServiceID,
		&i.ServiceUuid,
		&i.TenantID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.Endpoint,
		&i.Version,
		&i.Metadata,
		&i.RegisteredAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listServicesByTenant = `-- name: ListServicesByTenant :many
SELECT service_id, service_uuid, tenant_id, name, kind, status, endpoint, version, metadata, registered_at, created_by, updated_by, created_at, updated_at, deleted_at FROM services
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListServicesByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListServicesByTenant(ctx context.Context, arg ListServicesByTenantParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ServiceID,
			&i.ServiceUuid,
			&i.TenantID,
			&i.Name,
			&i.Kind,
			&i.Status,
			&i.Endpoint,
			&i.Version,
			&i.Metadata,
			&i.RegisteredAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteService = `-- name: SoftDeleteService :exec
UPDATE services
SET deleted_at = now(), updated_at = now()
WHERE service_uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteService(ctx context.Context, serviceUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteService, serviceUuid)
	return err
}

const updateServiceStatus = `-- name: UpdateServiceStatus :one
UPDATE services
SET status = $2,
    endpoint = $3,
    registered_at = $4,
    updated_at = now()
WHERE service_uuid = $1 AND deleted_at IS NULL
RETURNING service_id, service_uuid, tenant_id, name, kind, status, endpoint, version, metadata, registered_at, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateServiceStatusParams struct {
	ServiceUuid  uuid.UUID          `json:"service_uuid"`
	Status       string             `json:"status"`
	Endpoint     string             `json:"endpoint"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}

func (q *Queries) UpdateServiceStatus(ctx context.Context, arg UpdateServiceStatusParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateServiceStatus,
		arg.ServiceUuid,
		arg.Status,
		arg.Endpoint,
		arg.RegisteredAt,
	)
	var i Service
	err := row.Scan(
		&i.ServiceID,
		&i.ServiceUuid,
		&i.TenantID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.Endpoint,
		&i.Version,
		&i.Metadata,
		&i.RegisteredAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
