// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTenants = `-- name: CountTenants :one
SELECT count(*) FROM tenants
WHERE deleted_at IS NULL
`

func (q *Queries) CountTenants(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTenants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, display_name, status, is_system, auth_tenant_uuid, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING tenant_id, tenant_uuid, auth_tenant_uuid, name, display_name, status, is_system, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateTenantParams struct {
	Name           string      `json:"name"`
	DisplayName    string      `json:"display_name"`
	Status         string      `json:"status"`
	IsSystem       bool        `json:"is_system"`
	AuthTenantUuid pgtype.UUID `json:"auth_tenant_uuid"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.DisplayName,
		arg.Status,
		arg.IsSystem,
		arg.AuthTenantUuid,
		arg.Metadata,
	)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.TenantUuid,
		&i.AuthTenantUuid,
		&i.Name,
		&i.DisplayName,
		&i.Status,
		&i.IsSystem,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSystemTenant = `-- name: GetSystemTenant :one
SELECT tenant_id, tenant_uuid, auth_tenant_uuid, name, display_name, status, is_system, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM tenants
WHERE is_system = TRUE AND deleted_at IS NULL
LIMIT 1
`

// The platform's root tenant — the single required system tenant.
func (q *Queries) GetSystemTenant(ctx context.Context) (Tenant, error) {
	row := q.db.QueryRow(ctx, getSystemTenant)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.TenantUuid,
		&i.AuthTenantUuid,
		&i.Name,
		&i.DisplayName,
		&i.Status,
		&i.IsSystem,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT tenant_id, tenant_uuid, auth_tenant_uuid, name, display_name, status, is_system, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM tenants
WHERE tenant_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantByID(ctx context.Context, tenantID int64) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, tenantID)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.TenantUuid,
		&i.AuthTenantUuid,
		&i.Name,
		&i.DisplayName,
		&i.Status,
		&i.IsSystem,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantByName = `-- name: GetTenantByName :one
SELECT tenant_id, tenant_uuid, auth_tenant_uuid, name, display_name, status, is_system, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM tenants
WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantByName(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByName, name)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.TenantUuid,
		&i.AuthTenantUuid,
		&i.Name,
		&i.DisplayName,
		&i.Status,
		&i.IsSystem,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantByUUID = `-- name: GetTenantByUUID :one
SELECT tenant_id, tenant_uuid, auth_tenant_uuid, name, display_name, status, is_system, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM tenants
WHERE tenant_uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantByUUID(ctx context.Context, tenantUuid uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByUUID, tenantUuid)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.TenantUuid,
		&i.AuthTenantUuid,
		&i.Name,
		&i.DisplayName,
		&i.Status,
		&i.IsSystem,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT tenant_id, tenant_uuid, auth_tenant_uuid, name, display_name, status, is_system, metadata, created_by, updated_by, created_at, updated_at, deleted_at FROM tenants
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTenantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.TenantID,
			&i.TenantUuid,
			&i.AuthTenantUuid,
			&i.Name,
			&i.DisplayName,
			&i.Status,
			&i.IsSystem,
			&i.Metadata,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTenant = `-- name: SoftDeleteTenant :exec
UPDATE tenants
SET deleted_at = now(), updated_at = now()
WHERE tenant_uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTenant(ctx context.Context, tenantUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTenant, tenantUuid)
	return err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET display_name = $2,
    status = $3,
    auth_tenant_uuid = $4,
    metadata = $5,
    updated_at = now()
WHERE tenant_uuid = $1 AND deleted_at IS NULL
RETURNING tenant_id, tenant_uuid, auth_tenant_uuid, name, display_name, status, is_system, metadata, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateTenantParams struct {
	TenantUuid     uuid.UUID   `json:"tenant_uuid"`
	DisplayName    string      `json:"display_name"`
	Status         string      `json:"status"`
	AuthTenantUuid pgtype.UUID `json:"auth_tenant_uuid"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.TenantUuid,
		arg.DisplayName,
		arg.Status,
		arg.AuthTenantUuid,
		arg.Metadata,
	)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.TenantUuid,
		&i.AuthTenantUuid,
		&i.Name,
		&i.DisplayName,
		&i.Status,
		&i.IsSystem,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
