#!/usr/bin/env bash
set -euo pipefail

KEYDIR="${1:-keys}"
mkdir -p "$KEYDIR"

PRIVATE_KEY="$KEYDIR/private.pem"
PUBLIC_KEY="$KEYDIR/public.pem"
OUTFILE="$KEYDIR/jwt_env_vars.txt"

openssl genpkey -algorithm RSA -out "$PRIVATE_KEY" -pkeyopt rsa_keygen_bits:2048 2>/dev/null
openssl rsa -pubout -in "$PRIVATE_KEY" -out "$PUBLIC_KEY" 2>/dev/null

cat > "$OUTFILE" <<EOF
# Generated by scripts/generate-jwt-keys.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
JWT_PRIVATE_KEY="$(awk '{printf "%s\\n", $0}' "$PRIVATE_KEY" | sed 's/\\n$//')"
JWT_PUBLIC_KEY="$(awk '{printf "%s\\n", $0}' "$PUBLIC_KEY" | sed 's/\\n$//')"

APP_ENCRYPTION_KEY=base64:$(openssl rand -base64 32)
HMAC_SECRET_KEY=base64:$(openssl rand -base64 32)
EOF

echo "Keys written to $KEYDIR/"
echo "Add to your .env with: cat $OUTFILE >> .env"
